export const requestType = {
    POST: "post",
    GET: "get",
    PUT: "put",
    DELETE: "delete",
};
export const endPoints = {
    loginAdmin:'loginAdmin',
    addProduct:"addProduct",
    getAllProducts:"getAllProducts",
    updateProduct:"updateProduct",
    deleteProduct:"deleteProduct",
    createCategory:"createCategory",
    getCategory:"getCategory",
    getAllCategories:"getAllCategories",
    updateCategory:"updateCategory",
    deleteCategory:"deleteCategory",
    getAllMaterials:"getAllMaterials",
    createMaterial:"createMaterial",
    updateMaterial:"updateMaterial",
    deleteMaterial:"deleteMaterial",
    getAllMaterialsAdmin:"getAllMaterialsAdmin",
    getAllCategoriesAdmin:"getAllCategoriesAdmin",
    getAllProductsByUser : "getAllProductsByUser",
    getMaterial : "getMaterial",
    registerUser : "registerUser",
    loginUser : "loginUser",
    sendCode : "sendCode",
    proceedPayment : "proceedPayment",
    calculateScore:"calculate-score",
    getAllUsersByAdmin:"getAllUsersByAdmin",
    getProductDetailsById: "getProductDetailsById",
    sendCodeUser: "sendCodeUser",
    resetPasswordUser: "resetPasswordUser",
    sendCodeAdmin: "sendCodeAdmin",
    resetPasswordAdmin: "resetPasswordAdmin",
    contactUs: "contactUs",
    createDepartment:"createDepartment",
    getDepartment:"getDepartment",
    getAllDepartmentsAdmin:"getAllDepartmentsAdmin",
    getAllDepartments:"getAllDepartments",
    updateDepartment:"updateDepartment",
    deleteDepartment:"deleteDepartment",
    getUserDetailsById:"getUserDetailsById",
    cancelSubscription:"cancelSubscription",
    subscribe:"subscribe",
};